spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:ngfenglong/springboot-ms-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///Users/[path]/config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071