apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: zell1502/message:s4
          ports:
            - containerPort: 9010
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: MESSAGE_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: message
spec:
  selector:
    app: message
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010
